/*
  hale: support for minimalist scientific visualization
  Copyright (C) 2014  University of Chicago

  This software is provided 'as-is', without any express or implied
  warranty. In no event will the authors be held liable for any damages
  arising from the use of this software. Permission is granted to anyone to
  use this software for any purpose, including commercial applications, and
  to alter it and redistribute it freely, subject to the following
  restrictions:

  1. The origin of this software must not be misrepresented; you must not
  claim that you wrote the original software. If you use this software in a
  product, an acknowledgment in the product documentation would be
  appreciated but is not required.

  2. Altered source versions must be plainly marked as such, and must not be
  misrepresented as being the original software.

  3. This notice may not be removed or altered from any source distribution.
*/

#ifndef HALE_INCLUDED
#define HALE_INCLUDED

#include <iostream>

#include <teem/meet.h> /* will include all other teem headers */

/* we don't #define GLM_FORCE_RADIANS here because who knows
   what Hale users will expect or need; see privateHale.h */
#include <glm/glm.hpp>

// Let GLFW sort out out how to include the OpenGL3 headers
#define GLFW_INCLUDE_GLCOREARB
/* NB: on at least one Linux system that was missing GL/glcorearb.h,
   GLK followed advice from here:
   http://oglplus.org/oglplus/html/oglplus_getting_it_going.html and
   manually put glcorearb.h in /usr/include/GL, however the info here:
   https://www.opengl.org/registry/api/readme.pdf suggests that all
   those headers should be locally re-generated by a script */
#include <GLFW/glfw3.h>

namespace Hale {

/*
** viewerMode* enum
**
** The GUI modes that the viewer can be in. In Fov and Depth (distance from
** near to far adjusted), the eye and look-at point are both fixed. The eye
** moves around a fixed look-at point in the Rotate and Dolly modes. The eye
** and look-at points move together in the Translate modes.
*/
enum {
  viewerModeUnknown,     /*  0 */
  viewerModeNone,        /*  1: buttons released => no camera interaction */
  viewerModeFov,         /*  2: standard "zoom" */
  viewerModeDepth,       /*  3: adjust distance between near and far planes */
  viewerModeRotateUV,    /*  4: usual rotate (around look-at point) */
  viewerModeRotateU,     /*  5: rotate around horizontal axis */
  viewerModeRotateV,     /*  6: rotate around vertical axis */
  viewerModeRotateN,     /*  7: in-plane rotate (around at point) */
  viewerModeDolly,       /*  8: fix at, move from, adjust fov: the effect is
                                direct control on the amount of perspective */
  viewerModeTranslateUV, /*  9: usual translate */
  viewerModeTranslateU,  /* 10: translate only horizontal */
  viewerModeTranslateV,  /* 11: translate only vertical */
  viewerModeTranslateN,  /* 12: translate from *and* at along view direction */
  viewerModeLast
};
#define HALE_VIEWER_MODE_MAX 12

enum {
  finishingStatusUnknown,      /* 0 */
  finishingStatusNot,          /* 1: we're still running */
  finishingStatusOkay,         /* 2: we're quitting gracefully */
  finishingStatusError,        /* 3: we're exiting with error */
  finishingStatusLast
};
#define HALE_FINISHING_STATUS_MAX 3

/* enums.cpp */
extern airEnum *viewerMode;
extern airEnum *finishingStatus;

/* utils.cpp */
extern bool finishing;
extern int init();
extern void done();
extern void errorGLFW(int errnum, const char *errstr);
extern GLuint limnToGLPrim(int type);

/* Camera.cpp: like Teem's limnCamera but simpler: there is no notion of
   image-plane distance (because the range along U and V is wholly
   determined by fov and aspect), there is no control of right-vs-left
   handed coordinates (it is always right-handed: U increases to the right,
   V increases downward), and clipNear and clipFar are always relative to
   look-at point.
   HEY as short-term hack, near and far are relative to eye */
class Camera {
 public:
  explicit Camera(glm::vec3 from = glm::vec3(3,4,5),
                  glm::vec3 at = glm::vec3(0,0,0),
                  glm::vec3 up = glm::vec3(0,0,1),
                  double fov = 0.8f,
                  double aspect = 1.3333333,
                  double clipNear = 5, // -2,
                  double clipFar = 9, // 2,
                  bool orthographic = false);

  /* set/get verbosity level */
  void verbose(int);
  int verbose();

  /* set everything at once, as if at initialization */
  void init(glm::vec3 from, glm::vec3 at, glm::vec3 up,
            double fov, double aspect,
            double clipNear, double clipFar,
            bool orthographic);

  /* set/get world-space look-from, look-at, and pseudo-up */
  void from(glm::vec3); glm::vec3 from();
  void at(glm::vec3);   glm::vec3 at();
  void up(glm::vec3);   glm::vec3 up();

  /* setters, getters */
  void fov(double);        double fov();
  void aspect(double);     double aspect();
  void clipNear(double);   double clipNear();
  void clipFar(double);    double clipFar();
  void orthographic(bool); bool orthographic();

  /* the (world-to-)view and projection transforms
     determined by the above parameters */
  glm::mat4 view();
  glm::mat4 project();
  const float *viewPtr();
  const float *projectPtr();

  /* basis vectors of view space */
  glm::vec3 U();
  glm::vec3 V();
  glm::vec3 N();

 private:
  int _verbose;

  /* essential camera parameters */
  glm::vec3 _from, _at, _up;
  double _fov, _aspect, _clipNear, _clipFar;
  bool _orthographic;

  /* derived parameters */
  glm::vec3 _uu, _vv, _nn; // view-space basis
  glm::mat4 _view, _project;

  void updateView();
  void updateProject();
};

/* Viewer.cpp: Viewer contains and manages a GLFW window, including the
   camera that defines the view within the viewer.  We intercept all
   the events in order to handle how the camera is updated */
class Viewer {
 public:
  explicit Viewer(int width,  int height, const char *label);
  ~Viewer();

  /* the camera we update with user interactions */
  Camera camera;

  /* set/get verbosity level */
  void verbose(int);
  int verbose();

  /* get width and height of window in screen-space, which is not always
     the same as dimensions of frame buffer (on high-DPI displays, the
     frame buffer size is larger than the nominal size of the window).
     There are no methods for setting width and height because that's
     handled by responding to GLFW resize events */
  int width();
  int height();

  /* set/get whether to fix the "up" vector during camera movements */
  void upFix(bool);
  bool upFix();

  /* swap render buffers in window */
  void bufferSwap();

  GLFWwindow *_window; // the window we manage
 private:
  bool _button[2];     // true iff button (left:0, right:1) is down
  int _verbose;
  bool _upFix;
  int _mode;           // from Hale::viewerMode* enum
  // GLFWwindow *_window; // the window we manage
  int _pixDensity,
    _widthScreen, _heightScreen,
    _widthBuffer, _heightBuffer;
  double _lastX, _lastY; // last clicked position, in screen space

  static void cursorPosCB(GLFWwindow *gwin, double xx, double yy);
  static void framebufferSizeCB(GLFWwindow *gwin, int newWidth, int newHeight);
  static void keyCB(GLFWwindow *gwin, int key, int scancode, int action, int mods);
  static void windowCloseCB(GLFWwindow *gwin);
  static void mouseButtonCB(GLFWwindow *gwin, int button, int action, int mods);

  void shapeUpdate();
  void cameraUpdate();
};

} // namespace Hale

#endif /* HALE_INCLUDED */
